-- 0002_summaries.sql
-- Feature 3 (Topical summaries). One row per (founder, topic) pair.
-- Generated by scripts/generate-summaries.ts; static-ish content (re-runs
-- replace existing rows for the same prompt_version).

CREATE TABLE IF NOT EXISTS summaries (
  founder_slug    TEXT NOT NULL,
  topic_slug      TEXT NOT NULL,
  topic_label     TEXT NOT NULL,
  /*
   * The summary body in the founder's voice. Includes [cite:N] markers
   * indexing into the citations JSONB array below. Validated with the same
   * fail-closed citation validator used by the live panel.
   */
  content         TEXT NOT NULL,
  /*
   * One row per [cite:N] marker:
   *   { "index": 0, "post_url": "...", "post_title": "...", "paragraph_idx": 12 }
   * Used by the summary page UI to render clickable citations.
   */
  citations       JSONB NOT NULL DEFAULT '[]'::jsonb,
  /*
   * Bumped on persona prompt changes. Re-running the generator with a new
   * prompt_version writes new rows (we keep history); the latest version is
   * surfaced in the UI.
   */
  prompt_version  TEXT NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tokens_in       INT NOT NULL DEFAULT 0,
  tokens_out      INT NOT NULL DEFAULT 0,
  PRIMARY KEY (founder_slug, topic_slug, prompt_version)
);

-- Topic-first lookup for "How do different founders think about X?"
CREATE INDEX IF NOT EXISTS summaries_topic_slug
  ON summaries (topic_slug);

-- Newest-first lookup for the generator (find the latest version per pair).
CREATE INDEX IF NOT EXISTS summaries_latest
  ON summaries (founder_slug, topic_slug, generated_at DESC);
